print('бесконечность', 'не', 'предел', '!', sep='_')
print('бесконечность_не_предел!')
print('бесконечность', 'не', 'предел', sep='_', end='!')
print('бесконечность', 'не', 'предел', sep='_', end='')
print('!')
print('бесконечность_не_предел', end='')
print('!')
print('бесконечность_','не_', 'предел!', sep='', end='')
print('YES', sep='!', end='#')
print('NO', sep='#', end='!')
print('a', 'b', 'c', sep='*')
print('d', 'e', 'f', sep='**', end='')
print('g', 'h', 'i', sep='+', end='%')
print('j', 'k', 'l', sep='-', end='\n')
print('m', 'n', 'o', sep='/', end='!')
print('p', 'q', 'r', sep='1', end='%')
print('s', 't', 'u', sep='&', end='\n')
print('v', 'w', 'x', sep='%')
print('y', 'z', sep='/', end='!')
print('I', 'like', 'Python', sep='***')